### ISSUE TITLE
egg-soft-rpc ts 项目不能用生成的.js文件吗

### ISSUE THREAD

**Issue by 345316222** [eggjs/egg-rpc-generator#17]
我是用 -ts 文件模式， 调用 egg-rpc-generator 生成 ProtoService.js 文件，作为客户端， run dev 后启动报错， options.registry or options.serverHost at least set one 这句话什么意思？在package.json里面设置rpc吗？如果是，已经设置了  

```
config.sofaRpc = {
    registry: {
      address: '127.0.0.1:2181', // 根据实际情况配置
    },
    client: {
      responseTimeout: 3000,
    },
  };
```
```

/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_sofa-rpc-node@1.18.0@sofa-rpc-node/lib/client/consumer.js:25
    assert(options.allowMock || options.serverHost || options.registry, '[RpcConsumer] options.registry or options.serverHost at least set one');
    ^
AssertionError [ERR_ASSERTION]: [RpcConsumer] options.registry or options.serverHost at least set one
    at new RpcConsumer (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_sofa-rpc-node@1.18.0@sofa-rpc-node/lib/client/consumer.js:25:5)
    at EggRpcClient.createConsumer (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_sofa-rpc-node@1.18.0@sofa-rpc-node/lib/client/client.js:97:18)
    at EggRpcClient.createConsumer (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-rpc-base@1.3.1@egg-rpc-base/lib/client.js:41:18)
    at module.exports.app (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/app/proxy/ProtoService.js:10:34)
    at getExports (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-core@4.17.4@egg-core/lib/loader/file_loader.js:220:15)
    at ContextLoader.parse (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-core@4.17.4@egg-core/lib/loader/file_loader.js:158:25)
    at ContextLoader.load (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-core@4.17.4@egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToContext (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-core@4.17.4@egg-core/lib/loader/egg_loader.js:408:28)
    at module.exports.app (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-rpc-base@1.3.1@egg-rpc-base/app.js:7:14)
    at Hook.configDidLoad (/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_egg-core@4.17.4@egg-core/lib/lifecycle.js:91:9)
[2020-05-14 07:41:42.611] [cfork:master:63327] worker:63352 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2020-05-14 07:41:42.612] [cfork:master:63327] don't fork, because worker:63352 will be kill soon
2020-05-14 07:41:42,613 INFO 63327 [master] app_worker#1:63352 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2020-05-14 07:41:42.613] [cfork:master:63327] worker:63352 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
```

**Comment by gxcsoccer** [comment]
参考： https://github.com/eggjs/egg/issues/4302#issuecomment-629117775
